# coding: utf-8

"""
    gnomock

    `gnomock` is an HTTP wrapper for [Gnomock](https://github.com/orlangure/gnomock) integration and end-to-end testing toolkit. It allows to use Gnomock outside of Go ecosystem. Not all Gnomock features exist in this wrapper, but official presets, as well as basic general configuration, are supported.   # noqa: E501

    The version of the OpenAPI document: 1.4.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.memcached import Memcached  # noqa: E501
from openapi_client.rest import ApiException

class TestMemcached(unittest.TestCase):
    """Memcached unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Memcached
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.memcached.Memcached()  # noqa: E501
        if include_optional :
            return Memcached(
                values = {"foo":"YmFy","baz":"NDI=","meh":"My4xNA=="}, 
                version = 'latest'
            )
        else :
            return Memcached(
        )

    def testMemcached(self):
        """Test Memcached"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
