# coding: utf-8

"""
    gnomock

    `gnomock` is an HTTP wrapper for [Gnomock](https://github.com/orlangure/gnomock) integration and end-to-end testing toolkit. It allows to use Gnomock outside of Go ecosystem. Not all Gnomock features exist in this wrapper, but official presets, as well as basic general configuration, are supported.   # noqa: E501

    The version of the OpenAPI document: 0.1.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import gnomock
from gnomock.models.mysql_request import MysqlRequest  # noqa: E501
from gnomock.rest import ApiException

class TestMysqlRequest(unittest.TestCase):
    """MysqlRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test MysqlRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = gnomock.models.mysql_request.MysqlRequest()  # noqa: E501
        if include_optional :
            return MysqlRequest(
                preset = gnomock.models.mysql.Mysql(
                    db = 'mydb', 
                    user = 'gnomock', 
                    password = 'gnomick', 
                    queries = ["create table foo(bar int)","insert into foo(bar) values(1)"], 
                    queries_file = '/home/gnomock/project/testdata/mysql/queries', ), 
                options = gnomock.models.options.Options(
                    env = [
                        'ENV_VAR_NAME=some-value'
                        ], 
                    tag = 'latest', )
            )
        else :
            return MysqlRequest(
        )

    def testMysqlRequest(self):
        """Test MysqlRequest"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
